# @package _global_

defaults:
  - _self_
  - experiment: setfitlinear
  - optimisation: ls
  - hydra: default
  - paths: default
  - extras: default
    #- override hydra/launcher: submitit_slurm


seed: 42


trainerHardwer:
  use_cuda: True

